/*
 * tdp-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ComponentUpdate {
    #[serde(rename = "message")]
    pub message: String,
    /// A free form object used as a dictionnary in TDP sdk. You can use any kind of data understood as a JSON object
    #[serde(rename = "variables")]
    pub variables: serde_json::Value,
}

impl ComponentUpdate {
    pub fn new(message: String, variables: serde_json::Value) -> ComponentUpdate {
        ComponentUpdate {
            message,
            variables,
        }
    }
}


