/*
 * tdp-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeployStatus {
    #[serde(rename = "message")]
    pub message: String,
}

impl DeployStatus {
    pub fn new(message: String) -> DeployStatus {
        DeployStatus {
            message,
        }
    }
}


