/*
 * tdp-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeployRequest {
    /// List of operations used as targets on the dag generation, mutually exclusive with `sources`.
    #[serde(rename = "targets", skip_serializing_if = "Option::is_none")]
    pub targets: Option<Vec<String>>,
    /// List of operations used as sources on the dag generation, mutually exclusive with `targets`.
    #[serde(rename = "sources", skip_serializing_if = "Option::is_none")]
    pub sources: Option<Vec<String>>,
    /// Controls how the filter expression must be interpreted.
    #[serde(rename = "filter_type", skip_serializing_if = "Option::is_none")]
    pub filter_type: Option<Box<crate::models::FilterTypeEnum>>,
    /// Expression which will match on the operation list generated from the dag. Only operations matching will be kept for the deployment.
    #[serde(rename = "filter_expression", skip_serializing_if = "Option::is_none")]
    pub filter_expression: Option<String>,
    /// Controls whether or not start operations will be replaced by a restart operation.
    #[serde(rename = "restart", skip_serializing_if = "Option::is_none")]
    pub restart: Option<bool>,
}

impl DeployRequest {
    pub fn new() -> DeployRequest {
        DeployRequest {
            targets: None,
            sources: None,
            filter_type: None,
            filter_expression: None,
            restart: None,
        }
    }
}


