/*
 * tdp-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FilterTypeEnum : An enumeration.

/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FilterTypeEnum {
    #[serde(rename = "regex")]
    Regex,
    #[serde(rename = "glob")]
    Glob,

}

impl ToString for FilterTypeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Regex => String::from("regex"),
            Self::Glob => String::from("glob"),
        }
    }
}

impl Default for FilterTypeEnum {
    fn default() -> FilterTypeEnum {
        Self::Regex
    }
}




