/*
 * tdp-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OperationLog {
    #[serde(rename = "operation")]
    pub operation: String,
    #[serde(rename = "start_time")]
    pub start_time: String,
    #[serde(rename = "end_time")]
    pub end_time: String,
    #[serde(rename = "state")]
    pub state: crate::models::StateEnum,
    #[serde(rename = "logs")]
    pub logs: std::path::PathBuf,
}

impl OperationLog {
    pub fn new(operation: String, start_time: String, end_time: String, state: crate::models::StateEnum, logs: std::path::PathBuf) -> OperationLog {
        OperationLog {
            operation,
            start_time,
            end_time,
            state,
            logs,
        }
    }
}


