/*
 * tdp-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Operation {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "collection_name", skip_serializing_if = "Option::is_none")]
    pub collection_name: Option<String>,
    #[serde(rename = "depends_on", skip_serializing_if = "Option::is_none")]
    pub depends_on: Option<Vec<String>>,
    #[serde(rename = "noop", skip_serializing_if = "Option::is_none")]
    pub noop: Option<bool>,
    #[serde(rename = "service")]
    pub service: String,
    #[serde(rename = "action")]
    pub action: String,
    #[serde(rename = "component", skip_serializing_if = "Option::is_none")]
    pub component: Option<String>,
}

impl Operation {
    pub fn new(name: String, service: String, action: String) -> Operation {
        Operation {
            name,
            collection_name: None,
            depends_on: None,
            noop: None,
            service,
            action,
            component: None,
        }
    }
}


