/*
 * tdp-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OperationsRequest {
    /// List of operations to be run on the cluster. Can be operations outside of the dag.
    #[serde(rename = "operations")]
    pub operations: Vec<String>,
}

impl OperationsRequest {
    pub fn new(operations: Vec<String>) -> OperationsRequest {
        OperationsRequest {
            operations,
        }
    }
}


