/*
 * tdp-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceUpdateResponse {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "version")]
    pub version: String,
}

impl ServiceUpdateResponse {
    pub fn new(message: String, version: String) -> ServiceUpdateResponse {
        ServiceUpdateResponse {
            message,
            version,
        }
    }
}


