/*
 * tdp-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// StateEnum : An enumeration.

/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StateEnum {
    #[serde(rename = "Success")]
    Success,
    #[serde(rename = "Failure")]
    Failure,
    #[serde(rename = "Pending")]
    Pending,

}

impl ToString for StateEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Success => String::from("Success"),
            Self::Failure => String::from("Failure"),
            Self::Pending => String::from("Pending"),
        }
    }
}

impl Default for StateEnum {
    fn default() -> StateEnum {
        Self::Success
    }
}




